---
# tasks file for investigate

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install investigation tools
  ansible.builtin.package:
    name: "{{ investigate_packages }}"
    state: present
